name: flutter_firebase_analytics
description: Google Analytics for Firebase.
version: 0.0.1
authors:
  - Mike Diarmid <mike@invertase.io>
  - Elliot Hesp <elliot@invertase.io>
homepage: https://invertase.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_firebase_app:
    path: ../app

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.invertase.firebase.analytics
    pluginClass: FlutterFirebaseAnalyticsPlugin
