---
name: React Native Firebase
npm: react-native-firebase
repository: invertase/react-native-firebase
description: React Native Firebase is a light-weight javascript layer connecting you
  to the native Firebase SDKs for both iOS and Android which mirrors the official
  Firebase Web SDK as closely as possible.
theme:
  logo: '//static.invertase.io/assets/React-Native-Firebase.svg'
  favicon: '//static.invertase.io/assets/react-native-firebase-favicon.png'
  primary: '#e88534'
  secondary: '#F8C449'
social:
  twitter: 'https://twitter.com/rnfirebase'
  discord: 'https://invertase.link/discord'
versions:
  latest: v6
  branches:
    v6: '@salakar/v6/storage'
menu:
  - text: v6.x.x
    to: '/v6'
  - text: Guides
    to: '/guides'
  - text: FAQs
    to: '/faqs'
  - text: Showcase
    to: '/showcase'
